#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made. 
*
* The version of the OpenAPI document: 0.14.1
* Contact: support@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol TGWatchlistMatch
@end

@interface TGWatchlistMatch : TGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSArray<NSString*>* altNames;

@property(nonatomic) NSString* federalRegisterNotice;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* sourceInformationUrl;

@property(nonatomic) NSString* sourceListUrl;

@property(nonatomic) NSString* list;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* category;

@property(nonatomic) NSString* street1;

@property(nonatomic) NSString* street2;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* state;

@property(nonatomic) NSString* country;

@property(nonatomic) NSString* notes;

@property(nonatomic) NSString* frc;

@property(nonatomic) NSString* start;

@property(nonatomic) NSString* end;

@property(nonatomic) NSString* frserve;

@property(nonatomic) NSString* optionalID;

@property(nonatomic) NSString* alertType;

@property(nonatomic) NSString* pairStatus;

@property(nonatomic) NSString* pairReason;

@property(nonatomic) NSString* pairComments;

@property(nonatomic) NSString* applicationDisplayName;

@property(nonatomic) NSString* applicationId;

@property(nonatomic) NSString* clientId;

@property(nonatomic) NSString* clientKey;

@property(nonatomic) NSString* clientFullName;

@property(nonatomic) NSString* listKey;

@property(nonatomic) NSString* listName;

@property(nonatomic) NSString* listId;

@property(nonatomic) NSString* listVersion;

@property(nonatomic) NSString* listModifyDate;

@property(nonatomic) NSString* listProfileId;

@property(nonatomic) NSString* listProfileKey;

@property(nonatomic) NSString* linkSingleStringName;

@property(nonatomic) NSString* listParentSingleStringName;

@property(nonatomic) NSString* listCategory;

@property(nonatomic) NSString* listPepCategory;

@property(nonatomic) NSString* listDoBs;

@property(nonatomic) NSString* listCountries;

@property(nonatomic) NSString* rankString;

@property(nonatomic) NSString* ranktype;

@property(nonatomic) NSString* rankweight;

@property(nonatomic) NSString* pairLoadDate;

@property(nonatomic) NSString* eAddressTo;

@property(nonatomic) NSString* eAddressCc;

@property(nonatomic) NSString* origin;

@property(nonatomic) NSString* secondsviewed;

@property(nonatomic) NSString* initialUser;

@property(nonatomic) NSString* isPairParentFlag;

@property(nonatomic) NSString* pairMetSearchCriteriaFlag;

@property(nonatomic) NSString* editableDueToAssignmentFlag;

@property(nonatomic) NSString* modifyDate;

@property(nonatomic) NSString* modifiedByUser;

@property(nonatomic) NSString* pairReportType;

@property(nonatomic) NSString* finscanCategory;

@property(nonatomic) NSString* wrapperStatus;

@property(nonatomic) NSString* sourceLists;

@end
